# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Test with the dotnet CLI
        run: dotnet test EcoState.Test/EcoState.Test.csproj --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Extract Coverage Percentage from XML
        id: extract_coverage
        run: |
          COVERAGE_XML=$(find ./coverage -name "coverage.cobertura.xml")
          if [ -z "$COVERAGE_XML" ]; then
            echo "Error: coverage.cobertura.xml not found"
            exit 1
          fi

          TOTAL_LINES=$(xmllint --xpath "sum(//line[@condition-coverage='100%']/@count + //line[not(@condition-coverage)]/@count)" "$COVERAGE_XML")
          COVERED_LINES=$(xmllint --xpath "sum(//line[@condition-coverage])" "$COVERAGE_XML")
          # Calculate percentage
          COVERAGE_PERCENTAGE=$(( $(echo "scale=2; $COVERED_LINES / $TOTAL_LINES * 100" | bc) + 0.5 ))
          echo "COVERAGE_PERCENTAGE=$COVERAGE_PERCENTAGE" >> $GITHUB_ENV

        shell: bash

      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 4a7a6924fbbad82e9ee021b9e5205127
          filename: test.json
          label: Coverage
          message: ${{ env.COVERAGE_PERCENTAGE }}%
          color: yellow
