# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
        
    - name: Install dependencies
      run: dotnet restore
    
    - name: Test with the dotnet CLI
      run: dotnet test EcoState.Test/EcoState.Test.csproj --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Extract Coverage Percentage
      id: coverage_percentage
      run: |
        COVERAGE=$(grep "Total" ./coverage/TestResults/*/coverage.cobertura.xml | awk -F'line-rate="' '{print $2}' | awk -F'"' '{print $1}' | awk '{printf "%.2f", $1 * 100}')
        echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
        echo "Code Coverage: $COVERAGE%"

    - name: Use Coverage Percentage
      run: |
        echo "Coverage Percentage: ${{ steps.coverage_percentage.outputs.coverage }}%"
      
    - name: Set Coverage Percentage
      run: |
        COVERAGE=steps.coverage_percentage.outputs.coverage
        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
      shell: bash

    - name: Create Awesome Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 4a7a6924fbbad82e9ee021b9e5205127
        filename: test.json
        label: Coverage
        message: ${{ env.COVERAGE }}
        color: red
